### ISSUE TITLE
Not working in 2020.3.33f1

### ISSUE THREAD

**Issue by HelmuthWcs** [appodeal/appodeal-unity-demo#16]
I was trying update my app with the newest sdk and failed. So I tried this demo to try to learn what i am doing wrong.
To my surprise not even this simple demo is working.
Open this project in unity 2020.3.33.f1 export to Android. Some deprecated message and does not even build. Do you even test these builds?

**Comment by DmitriiFeshchenko** [comment]
Hi, @HelmuthWcs.

Sorry for such a long delay.

Please, note that this demo was built for Unity 2018.4 as the minimum supported version. The errors you faced are most likely related to Editor version change.

I've just set the project up and successfully built it for Android after making a few changes:
1. Reimported mainTemplate.gradle (It has changed since 2018.4 and is no longer valid)
2. Added Admob app id via Appodeal/Appodeal Settings tool at the top menu bar.

Also, check if you have the [correct Gradle plugin version](https://wiki.appodeal.com/en/unity/get-started#UnitySDK.GetStarted-Step2Step2.ProjectConfiguration) set in templates for this version of the Editor.

If you have any further questions, please, contact our [support team](https://faq.appodeal.com/en/articles/96628-technical-support) at any time.

If you believe there is a bug in our demo, submit a new issue with a detailed explanation of how to reproduce it.
